name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  mobx: ^2.1.4
  path_provider: ^2.0.14
  package_info_plus: ^3.1.0
  permission_handler: ^10.2.0
  flutter_mobx: ^2.0.6+5
  flutter_overlay_loader: ^2.0.0
  shared_preferences: ^2.1.0
  graphql_flutter:
  hive:
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.1.8
  mobx_codegen:

flutter:

  uses-material-design: true

  assets:
    - assets/images/signup/
    - assets/images/login/
    - assets/images/splash/
    - assets/icon/